feat: Add `CrateDB` module
testcontainers/testcontainers-rs-modules-community pull request #236
Opened 2024-10-20 11:34 UTC by surister

Solves #198 

cc @kneth

2024-10-24 16:36 UTC, mervyn-mccreight commented
Thanks for your contribution 🚀 
Can you please check the formatting plus the clippy errors?

2024-11-08 04:09 UTC, mervyn-mccreight commented
Seems like rustfmt is still failing

2024-11-14 23:20 UTC, CommanderStorm requested changes
Hi, sorry for the late reviews.

I usually would not review so late in the cycle, but I think the docs currently would not work as you intended.

2024-11-14 23:20 UTC, CommanderStorm commented on src/cratedb/mod.rs
> +/// http_port: 4200
```suggestion
/// - `super_user`: `crate`
/// - `password`: <empty>
/// - `pg_port`: `5432`
/// - `http_port`: `4200`
```

2024-11-14 23:20 UTC, CommanderStorm commented on src/cratedb/mod.rs
> +/// let rows = conn.query("SELECT 1 + 1", &[]).unwrap();
currently, this is not a doctest

```suggestion
/// ```
/// use testcontainers_modules::{postgres, testcontainers::runners::SyncRunner};
///
/// let postgres_instance = cratedb::CrateDB::default().start().unwrap();
///
/// let connection_string = format!(
///     "postgres://crate@{}:{}/postgres",
///     postgres_instance.get_host().unwrap(),
///     postgres_instance.get_host_port_ipv4(5432).unwrap()
/// );
///
/// let mut conn = postgres::Client::connect(connection_string, postgres::NoTls).unwrap();
/// let rows = conn.query("SELECT 1 + 1", &[]).unwrap();
/// # assert_eq!(rows.len(), 1);
/// ```
```

2024-11-14 23:20 UTC, CommanderStorm commented on src/cratedb/mod.rs
> +    /// Sets CrateDB's heap size, only increase it if you are testing big high volumes of data.
```suggestion
    /// Sets CrateDB's heap size
    /// 
    /// You may need to increase this if you are testing high volumes of data.
```

2024-11-14 23:20 UTC, CommanderStorm commented on src/cratedb/mod.rs
> +        &self.copy_to_sources
This is never set to anything other than `Vec::new`... Is this intentional?

2024-11-14 23:22 UTC, CommanderStorm commented on src/cratedb/mod.rs
> +    #[test]
This fixes the linting issue raised by rustfmt

```suggestion
    use super::*;
    use crate::testcontainers::{runners::SyncRunner, ImageExt};

    #[test]
```

2025-01-07 02:28 UTC, DDtKey commented
@surister hi 👋 

Thank you for the contribution first of all!

Could you take a look at comments from @CommanderStorm ? I find them reasonable and easy to fix

2025-05-28 19:47 UTC, surister commented
Sorry, this got lost, I get a *lot* of github notifications. Closing this in favor of #253

2025-05-28 19:47 UTC, closed without merging